### ISSUE TITLE
Command line utility for reading recipe files

### ISSUE THREAD

**Issue by loranallensmith** [loranallensmith/gitmethere#2]
It would be great have some way of creating scenarios in a more human-readable format like YAML that could be parsed into a Git repository.

Maybe something along the lines of:

``` yaml
name: merge-conflict
explanation: Some expository text in the README.md file
operations:
  - checkout-branch
    name: feature

  - create-file:
    name: conflict.md
    content: This line was added to the conflict.md file on the feature branch.

  - stage-changes:

  - create-commit:
    message: Add conflict.md file on master branch

  - create-file:
    - name: conflict.md
    - content: This line was added to the conflict.md file

  - stage-changes

  - create-commit
    - message: Create conflict.md file
```

I'm not completely sure of the format spec, but this would be a great help for creating libraries of recipes that could be easily tweaked for a particular example.
